### ISSUE TITLE
Lost information when converting to CUE

### ISSUE THREAD

**Issue by VorpalBlade** [AkBKukU/cd-ripping#4]
It appears some information is lost when converting the .toc to .cue. Specifically some of flags in sub channel Q (if I understand this correctly, which I most likely do not).

Here is an example .toc:

```
CD_ROM_XA


// Track 1
TRACK MODE2_RAW
NO COPY
DATAFILE "nero_5.5.5.6.bin" 35:16:17 // length in bytes: 373302384


// Track 2
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
SILENCE 00:02:00
FILE "nero_5.5.5.6.bin" #373302384 0 01:01:74
START 00:02:00


// Track 3
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
FILE "nero_5.5.5.6.bin" #373302384 01:01:74 00:59:74
```

Here is the .cue that was generated:

```
FILE "nero_5.5.5.6.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 35:16:17
  TRACK 03 AUDIO
    INDEX 01 36:18:16
```

As far as I can tell the copy flag and pre-emphasis flags were lost, and I see no provision for it in the CUE file format (at least as documented on Wikipedia). Intentionally changing the source `.toc` file to remove the `NO` from copy and pre-emphasis result in exactly the same cue file.

I tried using `cueconvert` from `cuetools` too but it errored out:
```
$ cueconvert -i toc nero_5.5.5.6.toc test.cue
11: syntax error
bad character '#'
16: syntax error
bad character '#'
25: syntax error
```

**Comment by AkBKukU** [comment]
I'm going to close this issue after looking into it again because it's going to require `cdrdao` to fix `toc2cue`.

`cdrdao` is the source of the `toc` files and they [continue](https://github.com/cdrdao/cdrdao/commit/5fa159bcf380746eaf6969e2fc683a011ddcc11f) to add new features to it meaning any external tools will never be able to keep up with converting the data fully. The only way it will ever make sense to have feature complete `toc` -> `cue` conversion will be if `cdrdao`'s own [toc2cue](https://github.com/cdrdao/cdrdao/blob/master/utils/toc2cue.cc) tool is brought up to feature parity with the rest of their tools.
